---
_extends: .github

repository:
  name: hs-tokstyle
  description: Style checker for TokTok C projects
  topics: linter, style, c

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - build-cabal
          - build-stack
          - cirrus-ci
          - Codacy Static Code Analysis
          - code-review/reviewable
