---
_extends: .github

repository:
  name: hs-tokstyle
  description: Style checker for TokTok C projects
  topics: linter, style, c

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy/PR Quality Review
          - Travis CI - Pull Request
          - code-review/reviewable
          - coverage/coveralls
