---
_extends: .github

repository:
  name: hs-tokstyle
  description: Style checker for TokTok C projects
  topics: linter, style, c

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "bazel-opt"
          - "build / cabal"
          - "build / stack"
