---
language: generic
dist: xenial
os: linux

env: PACKAGE=tokstyle TARGET=x86_64-linux

cache:
  timeout: 3
  directories:
    - $HOME/.stack

script:
  - bash <(travis_retry curl -s https://raw.githubusercontent.com/TokTok/hs-tools/master/bin/travis-haskell) script
  - ./expand_yacc.pl src/Tokstyle/Cimple/Parser.y src/Tokstyle/Cimple/Parser.y
  - stack install
  - tar zcf $PACKAGE-$TARGET-$TRAVIS_TAG.tar.gz -C $HOME/.local $(grep executable $PACKAGE.cabal | awk '{print "bin/"$2}')

deploy:
  provider: releases
  token:
    secure: "o1WqCKpiHuNK/YLwfMZyCVJAVYWs4Yz+4P3khO6gU7xfjVZ7Pbv62xdUJH57lfBIpAiPKOTD0mVrX/anfjrgKR3Ecr05oAj6JEtgLJm8G8fx4YepWpjc9k1ZhPxSkMmo6f5Y41uIyQsxYXxqWjQ4A3cvkxKv0LehXfPfWeQQgFL6ywl2r5oahmdqXha+v5+af+Gqpnsc9Ji8MlA6AOWCyT8A4I6QEqUgSqOqjEIojvpDGZkUCesv84pUjZ5D6Ur/3olAZmP+1he6HCy/IqExhAZeJ7QG91/VBG2G1iOsIU7TeTGi0ssoEV//pk7r9sIYJqbfCXcXbt9yokURgxb1A9y+1SMAfXm60USOM7hZRfZE95rnrm36bi60usUrf4TcdnwqlrpAgH+GfcA1ykdDLC0ghZWn/gnOHMAKivJuGuz4em9UUwKFQzF3Vh2Ud7bIJW3D2MynNDXB190qI6/pzccXyn+3LSRL7mdBUdvtCetRhfsczLPfggfY/ydRUzVyKvyMO3PCAH93vtbwkPzCUhMpNH514mo1DP0k0vZbDY5u9gwnhs40CMGbU8POvboMZwrQ2rPpsvfBUoWasU+gAQeAUPq5fzcUEbo53PUAiH063kPNmgQTO8guyBwm+kK5kzeQuNx4g7Vbf7tYM1Kh2fE10SVH15n/EepAl8Db7JY="
  file: $PACKAGE-$TARGET-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    repo: TokTok/hs-tokstyle
    tags: true
