name: ci

on:
  pull_request:
    branches: [master]

jobs:
  build:
    uses: TokTok/ci-tools/.github/workflows/haskell-ci.yml@master
    with:
      ghc-version: "8.10.3"
      cabal-version: "3.2"
